### ISSUE TITLE
The website does not launch

### ISSUE THREAD

**Issue by torstenkuhn77** [VeritasSoftware/AspNetCore.Security.Jwt.Microservice#1]
I can compile the microservice project. But when I try to launch the website I get a 404 error.

**Comment by VeritasSoftware** [comment]
Hi

It is not a web site.

It is an API.

You can make calls to it from Swagger.

Swagger will start when u start the API.

Regards.

Sent from my iPhone

On 26 Apr 2019, at 2:30 pm, Torsten Kuhn <notifications@github.com<mailto:notifications@github.com>> wrote:


I can compile the microservice project. But when I try to launch the website I get a 404 error.

**Comment by VeritasSoftware** [comment]
Hi

It is not a web site.

It is an API.

You can make calls to it from Swagger.

Swagger will start when u start the API.

Regards.

On 26 Apr 2019, at 2:30 pm, Torsten Kuhn <notifications@github.com<mailto:notifications@github.com>> wrote:


I can compile the microservice project. But when I try to launch the website I get a 404 error.

**Comment by VeritasSoftware** [comment]
see my earlier comments
